spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    #driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      minimum-idle: 2
      idle-timeout: 300000  # Aqui mato conexiones no usadas 5 mintuos y respeto el numero minimo de conexiones que son 2
      max-lifetime: 1800000
      register-mbeans: false #evito fugas DE HILOS del pool de hilos

  jpa:
    hibernate:
      ddl-auto: update