spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      minimum-idle: 8
      idle-timeout: 300000
      max-lifetime: 1800000
      register-mbeans: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

#  batch:
#    initialize-schema: always

#  sql:
#    init:
#      enabled: true
#      mode: always
#      platform: postgresql
#      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
